### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by ngobibibnbe** [waico/arimafd#1]
Currently i would like to use your python library, but I can't find any documentation on it. 
Can you provide me some relevant links on how to use your library please ?

**Comment by waico** [comment]
> Currently i would like to use your python library, but I can't find any documentation on it.
> Can you provide me some relevant links on how to use your library please ?

We have made an example.

**Comment by H-Sf** [comment]
Hello and thank you for this library that I discovered from your paper.
I am interested in using  the online arima prediction and the hyperparameters tuning.
Is it possible to provide a little help on how to use these functions.
Thank you very much in advance.

**Comment by KozitsinSlava** [comment]
Hello, you can read READMD.md at https://github.com/waico/arimafd at the section "Get started". 01.11.2021, 12:32, "H-Sf" ***@***.***>: Hello and thank you for this library that I discovered from your paper.I am interested in using the online arima prediction and the hyperparameters tuning.Is it possible to provide a little help on how to use these functions.Thank you very much in advance.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   -- Kind regards,Vyacheslav Kozitsin

**Comment by H-Sf** [comment]
Thank you very much.
